const STORAGE_KEYS = {
  settings: "moyu-settings",
  modelCache: "moyu-model-cache",
  currentSession: "moyu-current-session",
  sessions: "moyu-sessions",
  currentSessionId: "moyu-current-session-id",
  locale: "moyu-locale",
  sidebarCollapsed: "moyu-sidebar-collapsed",
  userRoles: "moyu-user-roles",
  theme: "moyu-theme",
};

const i18n = {
  "zh-CN": {
    "app.title": "MOYU - 模鱼空间",
    "brand.title": "MOYU-模鱼",
    "brand.sidebarTitle": "MOYU",
    "brand.subtitle": "开始模鱼，开始摸鱼！",
    "nav.create": "创建聊天",
    "nav.chatList": "聊天列表",
    "nav.settings": "设置",
    "nav.userRoleLibrary": "角色设定",
    "nav.skills": "技能",
    "skills.subtitle": "模型驱动的结构化提问技能，帮助你分析问题、梳理思路。",
    "skills.howToUse": "如何使用",
    "skills.usageHint": "在工作模式聊天中，模型会根据对话自动判断是否需要使用结构化提问。你也可以手动输入 <code>/skill</code> 触发。模型会通过交互式卡片逐步引导你回答问题，最多 5 个问题，每个问题提供 3 个选项和自定义输入。",
    "skills.availableSkills": "可用技能场景",
    "skills.sceneAnalysis": "需求分析",
    "skills.sceneDesign": "方案设计",
    "skills.sceneDebug": "问题排查",
    "skills.sceneSentiment": "情感分析",
    "skills.sceneCustom": "更多场景由模型自行判断",
    "skills.tips": "小贴士",
    "skills.tipManual": "输入 <code>/skill</code> 手动触发",
    "skills.tipCustom": "可以选择模型提供的选项，也可以自行输入",
    "skills.tipInterrupt": "中途发送普通消息即可退出结构化提问",
    "settings.sectionTitle": "设置分类",
    "settings.sectionHint": "先选择要调整的设置分组。",
    "settings.back": "返回",
    "settings.globalTab": "全局设置",
    "settings.assistantTab": "辅助 AI",
    "settings.apiTab": "接口设置",
    "settings.globalTitle": "全局设置",
    "settings.globalSubtitle": "调整整个应用通用的设置项。",
    "settings.assistantTitle": "辅助 AI",
    "settings.assistantSubtitle": "配置全局辅助模型，供设定优化、推荐输入等能力使用。",
    "settings.apiTitle": "接口设置",
    "settings.apiSubtitle": "选择一个接口，修改 Host / Key，获取该接口模型列表，并维护工作模型。",
    "settings.assistantModelTitle": "辅助模型",
    "settings.assistantModelHint": "从所有工作模型里选一个，作为全局辅助 AI 默认模型。",
    "settings.assistantModelLabel": "辅助模型",
    "settings.assistantModelPlaceholder": "请选择辅助模型",
    "settings.assistantModelEmpty": "请先在接口设置中勾选工作模型",
    "settings.themeTitle": "主题外观",
    "settings.themeHint": "选择深色或浅色界面主题。",
    "settings.themeLabel": "界面主题",
    "settings.theme.system": "跟随系统",
    "settings.theme.dark": "深色",
    "settings.theme.light": "浅色",
    "settings.languageTitle": "语言设置",
    "settings.languageHint": "控制整个应用当前使用的界面语言。",
    "settings.languageLabel": "界面语言",
    "settings.locale.zh-CN": "简体中文",
    "settings.locale.en-US": "English",
    "settings.startupTitle": "初始页面",
    "settings.startupHint": "控制刷新页面后默认进入哪一种主界面。",
    "settings.initialPageLabel": "启动时打开",
    "settings.initialPage.welcome": "默认欢迎页",
    "settings.initialPage.create": "创建新聊天",
    "settings.initialPage.lastChat": "最后一次聊天",
    "settings.globalBasicsTitle": "基础体验",
    "settings.globalBasicsHint": "先决定界面语言和进入应用后的默认落点。",
    "settings.devTitle": "开发者选项",
    "settings.devHint": "用于排查导演调度和会话流程问题。",
    "settings.debugModeLabel": "调试模式",
    "settings.debugModeHint": "开启后会在 console 中输出结构化调试日志。",
    "settings.mobileConsoleLabel": "移动端调试控制台",
    "settings.mobileConsoleHint": "开启后会在小屏或触屏设备自动加载 Eruda 调试工具。",
    "settings.globalDataTitle": "备份与恢复",
    "settings.globalDataHint": "导出整套设置，或从已有备份快速恢复当前环境。",
    "settings.globalDangerTitle": "危险操作",
    "settings.globalDangerHint": "清空本地所有会话与消息数据。这个动作不可撤销。",
    "settings.sessionTab": "会话设置",
    "settings.sessionTitle": "会话设置",
    "settings.sessionSubtitle": "调整自动压缩阈值与 Token 显示等会话相关选项。",
    "settings.compressThresholdLabel": "自动压缩阈值",
    "settings.compressThresholdHint": "导演上下文 Token 数超过此值后，在发送消息时自动触发压缩。",
    "settings.showTokenDisplayLabel": "显示 Token 用量",
    "settings.showTokenDisplayHint": "关闭后 AI 回复气泡底部将不再显示 Token 统计信息。",
    "settings.directorDispatchLabel": "导演纯调度",
    "settings.directorDispatchHint": "开启后导演只决定谁回答，不指挥 NPC 怎么演，NPC 自由发挥。",
    "settings.sessionContextTitle": "上下文与压缩",
    "settings.sessionContextHint": "控制上下文膨胀后的压缩时机，以及导演介入的深度。",
    "settings.markdownRenderLabel": "Markdown 渲染",
    "settings.markdownRenderHint": "关闭后工作模式将使用纯文本显示，不渲染 Markdown。",
    "settings.showLineNumbersLabel": "代码块行号",
    "settings.showLineNumbersHint": "在代码左侧显示行号。",
    "settings.sessionDisplayTitle": "显示与阅读",
    "settings.sessionDisplayHint": "决定消息渲染细节、代码可读性和 token 信息是否展示。",
    "settings.sessionTransferTitle": "会话迁移",
    "settings.sessionTransferHint": "导出全部会话做备份，或把旧归档重新导回当前本地库。",
    "settings.backupTitle": "设置备份",
    "settings.backupHint": "导出所有设置（含 API Key）为 JSON 文件，或从备份文件恢复。",
    "settings.exportBackup": "导出设置备份",
    "settings.importBackup": "导入设置备份",
    "settings.importSuccess": "设置已成功导入",
    "settings.importFailed": "导入失败：文件格式不正确",
    "settings.importFailedParse": "导入失败：无法解析备份文件",
    "settings.title": "接口设置",
    "settings.subtitle": "选择接口、维护 Host / Key、同步模型列表，并勾选工作模型。",
    "settings.hostLabel": "API Host",
    "settings.keyLabel": "API Key",
    "settings.configNameLabel": "接口名称",
    "settings.configNamePlaceholder": "例如 OpenAI 主账号 / 临时中转站",
    "settings.hostPlaceholder": "例如 https://api.openai.com/v1",
    "settings.keyPlaceholder": "sk-...",
    "settings.save": "保存设置",
    "settings.fetch": "获取模型列表",
    "settings.cachedModels": "缓存模型",
    "settings.clearCache": "清空当前缓存",
    "settings.savedConfigs": "接口列表",
    "settings.savedConfigsHint": "新增、切换并维护你的接口配置。",
    "settings.addConfig": "新增",
    "settings.searchLabel": "搜索模型",
    "settings.searchPlaceholder": "输入模型名筛选并点击选择工作模型",
    "settings.workModelsTitle": "工作模型",
    "settings.workModelsHint": "在右侧缓存模型区点击即可加入或移出工作模型。",
    "settings.clearWorkModels": "清空",
    "settings.workModelsEmpty": "请先获取模型列表",
    "create.title": "创建新聊天",
    "create.subtitle": "先选择会话模式，再填写设定和 ${entityType} 配置。",
    "create.editTitle": "编辑当前会话",
    "create.editSubtitle": "修改全局设定、导演模型、${entityType} 名称、模型与角色 Prompt，然后保存到当前会话。",
    "create.newSubtitle": "先选择会话模式，再填写设定和 ${entityType} 配置。",
    "create.editNavInfo": "会话信息",
    "create.editNavOverrides": "会话界面",
    "create.editNavAdvanced": "高级设置",
    "create.exitEdit": "退出编辑",
    "create.editSidebarTitle": "编辑当前会话",
    "create.editSidebarHint": "桌面端可从这里快速切换当前会话的编辑分区。",
    "create.overridesSubtitle": "调整只作用于当前会话的显示设定，不影响全局设置。",
    "create.overridesTitle": "会话界面",
    "create.overridesHint": "这里放只作用于当前会话的单独调校，不影响全局设置。",
    "create.overridesContextTitle": "上下文与调度",
    "create.overridesContextHint": "这些改动会即时保存，只作用于当前会话。",
    "create.overridesDisplayTitle": "显示与阅读",
    "create.overridesDisplayHint": "用来微调这个会话里的阅读体验，不影响别的房间。",
    "create.overridesModelThinkingLabel": "Agent 思考",
    "create.overridesModelThinkingHint": "控制当前会话里的 Agent 是否默认携带思考参数。",
    "create.overridesModelIconLabel": "模型 Logo",
    "create.overridesModelIconHint": "控制当前会话里 AI 名字左侧是否显示模型提供商 Logo。",
    "create.overrideReset": "跟随全局",
    "create.overrideUsingGlobal": "当前跟随全局",
    "create.overrideCustomized": "当前已单独设置",
    "create.overrideGlobalDefault": "全局默认：${value}",
    "create.overrideValueOn": "开启",
    "create.overrideValueOff": "关闭",
    "create.advancedSubtitle": "单独调节每个 Agent 的生成参数，仅影响当前会话。",
    "create.advancedTemperatureLabel": "温度 (temperature)",
    "create.saveBtn": "保存会话",
    "create.statusMaxNpc": "最多添加 5 个 ${entityType}",
    "create.statusNpcAdded": "已添加新的 ${entityType}",
    "create.statusMinNpc": "至少保留 ${n} 个 ${entityType}",
    "create.statusNpcDeleted": "${entityType} 已删除",
    "create.statusCreated": "会话已创建",
    "create.statusSaved": "会话设定已保存",
    "create.statusEditing": "正在编辑当前会话设定",
    "create.statusNotFound": "要编辑的会话不存在",
    "create.statusDirectorUnavailable": "导演模型所属接口不可用",
    "create.statusProcessing": "正在处理中...",
    "create.errorSelectConfig": "请先选择一个接口",
    "create.statusNpcCount": "请保持 ${min} 到 ${max} 个 ${entityType}",
    "create.errorSetup": "请先在设置中保存 API Host 和 Key",
    "create.errorWorkModels": "请先在设置中勾选工作模型",
    "create.errorGlobalPrompt": "请填写全局 Prompt",
    "create.errorDirector": "请选择导演模型",
    "create.errorNpcCount": "${entityType} 数量需要在 ${min} 到 ${max} 个之间",
    "create.errorNpcModel": "每个 ${entityType} 都必须选择模型",
    "create.modelPlaceholder": "请选择模型",
    "create.workModelsEmpty": "请先在设置中勾选工作模型",
    "create.modeLabel": "会话模式",
    "create.modeStory": "创作模式",
    "create.modeStoryHint": "面向剧情与角色互动，导演负责推进场景并调度 NPC",
    "create.modeChaos": "混沌模式",
    "create.modeChaosHint": "像社交软件群聊一样让多个 AI 自主接话、互喷、拱火和抢话",
    "create.betaTag": "Beta",
    "create.modeWork": "工作模式",
    "create.modeWorkHint": "面向协作分工，导演负责安排回答顺序和任务分配",
    "create.modeHint": "创建时选择会话模式；创建后永久锁定，无法切换。请谨慎选择！",
    "create.modeLockedHint": "当前会话模式已锁定；如需切换模式，请新建会话。",
    "create.globalPromptLabel": "全局 Prompt",
    "create.globalPromptPlaceholder": "描述这个聊天是做什么的、世界观是什么、所有 AI 都应该知道什么。",
    "create.directorLabel": "导演模型",
    "create.npcTitle": "${entityType} 配置",
    "create.npcSubtitle": "每个 ${entityType} 必须绑定一个模型，也可以填写独立人物 Prompt。",
    "create.addNpc": "添加 ${entityType}",
    "create.noDirectorHint": "单 ${entityType} 模式无需导演调度，${entityType} 将直接回复。",
    "create.noGlobalPromptHint": "单 ${entityType} 模式将 ${entityType} Prompt 作为全部上下文，无需额外全局设定。",
    "create.submit": "创建会话",
    "create.userRoleLabel": "你的角色",
    "create.userRolePlaceholder": "可选：你的身份、背景、说话风格",
    "create.userRoleSelect": "从角色设定中选择...",
    "roleLibrary.title": "角色设定",
    "roleLibrary.subtitle": "管理你的角色身份设定，方便在创建会话时快速选用。",
    "roleLibrary.addRole": "新增角色",
    "roleLibrary.roleName": "角色名称",
    "roleLibrary.roleDescription": "角色描述",
    "roleLibrary.roleNamePlaceholder": "例如：侦探 / 店主 / 军师",
    "roleLibrary.roleDescriptionPlaceholder": "描述你的角色身份、背景、性格、说话风格等。",
    "roleLibrary.empty": "还没有保存的角色，点击上方按钮新增。",
    "roleLibrary.saved": "角色已保存",
    "roleLibrary.deleted": "角色已删除",
    "roleLibrary.confirmDelete": "确定要删除角色「${name}」吗？",
    "roleLibrary.editRole": "编辑角色",
    "roleLibrary.save": "保存角色",
    "roleLibrary.cancel": "取消",
    "chat.inputPlaceholder": "输入你想说的话...",
    "chat.send": "发送",
    "chat.directorThinking": "导演思考",
    "chat.directorDispatch": "纯调度",
    "npc.unnamed": "未命名 ${entityType}",
    "npc.noModel": "未选择模型",
    "chat.globalPromptEmpty": "未填写",
    "chat.directorEmpty": "未选择",
    "chat.noNpcs": "暂无 NPC",
    "chat.metaExpand": "展开",
    "chat.metaCollapse": "收起",
    "chat.menuEditSession": "编辑会话",
    "chat.menuRestart": "重新开始",
    "chat.menuRename": "重命名",
    "chat.menuDelete": "删除聊天",
    "chat.menuExport": "导出会话",
    "chat.restartedFromExisting": "已基于原会话设定创建新的空白会话",
    "settings.exportSessionsTitle": "导出会话",
    "settings.exportSessionsHint": "将所有会话导出为 JSON 文件。",
    "settings.importSessionsTitle": "导入会话",
    "settings.importSessionsHint": "从 JSON 文件导入一个或多个会话。",
    "settings.importSessionsSuccess": "会话导入成功",
    "settings.importSessionsFailed": "导入失败：文件格式不正确",
    "settings.importSessionsPartial": "导入完成，其中 ${n} 个会话因数据异常被跳过",
    "drop.overlayGlobal": "松开以导入设置备份",
    "drop.overlaySession": "松开以导入会话文件",
    "drop.overlayAuto": "松开以导入文件",
    "drop.overlayChatAttachment": "松开以添加图片或 TXT 附件",
    "npc.nameLabel": "${entityType} 名称",
    "npc.namePlaceholder": "例如：侦探 / 店主 / 军师",
    "npc.modelLabel": "模型",
    "npc.promptLabel": "${entityType} Prompt",
    "npc.promptPlaceholder": "可选：人物口吻、秘密、目标、说话风格。",
    "npc.footer": "所有 ${entityType} 都会看到全局 Prompt 和完整聊天记录。",
    "npc.remove": "删除",
    "chat.currentSession": "当前会话",
    "chat.emptySessions": "还没有会话",
    "chat.noActiveSession": "还没有活动会话",
    "chat.generatingTitle": "生成标题中...",
    "chat.systemSpeaker": "系统",
    "chat.systemNoticeCreated": "会话已创建",
    "chat.globalPromptLabel": "全局设定",
    "chat.readyAfterCreate": "已就绪",
    "chat.thinkingLabel": "思考过程",
    "chat.welcomeIntro": "一个多 AI 剧场与角色对话实验场。",
    "chat.welcomeHint": "先在左侧设置接口与工作模型，再创建聊天开始模鱼。",
    "chat.regenerate": "重新生成",
    "chat.regenerateHint": "从您的最后一条消息重新生成",
    "chat.copy": "复制",
    "chat.copied": "已复制",
    "chat.stopped": "已中断",
    "chat.stoppedHint": "用户已手动中断",

    "debug.scope.director": "导演",
    "debug.scope.turn": "回合",
    "debug.scope.compress": "压缩",
    "debug.scope.npc": "NPC",
    "debug.scope.settings": "设置",
    "debug.scope.bootstrap": "启动",
    "debug.scope.stripThinking": "清理思考",
    "debug.msg.requestAttempt": "请求尝试",
    "debug.msg.rawResponse": "原始响应",
    "debug.msg.retry": "重试",
    "debug.msg.failed": "失败",
    "debug.msg.started": "已开始",
    "debug.msg.finished": "已完成",
    "debug.msg.aborted": "已中止",
    "debug.msg.toolbarIconPointerdown": "工具栏图标按下",
    "debug.msg.toolbarIconClick": "工具栏图标点击",
    "debug.msg.popoverClosedOutside": "弹窗因外部点击关闭",
    "debug.msg.regenerate": "从用户消息重新生成",
    "debug.msg.userMessageSubmitted": "用户消息已提交",
    "debug.msg.turnFailed": "回合失败",
    "debug.msg.directorTurnStarted": "导演回合开始",
    "debug.msg.directiveAccepted": "指令已接受",
    "debug.msg.transientNpcsUpdated": "临时NPC已更新",
    "debug.msg.respondersResolved": "响应者已确定",
    "debug.msg.npcRepliesCompleted": "NPC回复完成",
    "debug.msg.rawResponseReceived": "原始响应已接收",
    "debug.msg.invalidResponseRetrying": "无效响应，正在重试",
    "debug.msg.repairResponseAccepted": "修复响应已接受",
    "debug.msg.repairResponseFailed": "修复响应失败",
    "debug.msg.repairAttempt": "修复尝试",
    "debug.msg.repairRawResponse": "修复原始响应已接收",
    "debug.msg.compressionRequested": "压缩已请求",
    "debug.msg.compressionAborted": "压缩在开始前已中止",
    "debug.msg.compressionStarted": "压缩已开始",
    "debug.msg.compressionFinished": "压缩已完成",
    "debug.msg.compressionFailed": "压缩失败",
    "debug.msg.popoverMountSkipped": "弹窗挂载已跳过",
    "debug.msg.popoverMounted": "弹窗已挂载",
    "debug.msg.popoverRenderSkipped": "弹窗渲染已跳过",
    "debug.msg.popoverRendered": "弹窗已渲染",
    "debug.msg.popoverActionPointerdown": "弹窗操作按下",
    "debug.msg.popoverActionClick": "弹窗操作点击",
    "debug.msg.popoverActionBound": "弹窗操作已绑定",
    "debug.msg.popoverActionMissing": "渲染后弹窗操作缺失",
    "debug.msg.strippedRepeatedBlocks": "已清理重复块",
    "debug.msg.debugModeToggled": "调试模式已切换",
    "debug.msg.mobileDebugConsole": "移动端调试控制台已启用",
    "debug.msg.npcRetry": "${speaker} 首次调用返回空，正在重试...",

    "loading.start": "开始摸鱼",
    "settings.clearAllData": "清理所有会话消息",
    "settings.clearAllDataConfirm": "确定要清空所有会话和消息数据吗？此操作不可撤销！",
    "settings.clearAllDataConfirm2": "再次确认：所有聊天记录将被永久删除。",
    "settings.clearAllDataSuccess": "所有会话消息已清空",
    "settings.clearAllDataFailed": "清理失败：${message}",
    "chat.statusReady": "已就绪",
    "chat.statusProcessing": "正在处理中...",
    "chat.suggestHintNoAssistant": "请先在设置中配置辅助模型",
    "chat.suggestHintNeedReply": "需要先等 AI 回复后才能获取推荐回复",
    "chat.thinkingSettings": "思考设置",
    "chat.deepThinking": "深度思考",
    "chat.depthLow": "低",
    "chat.depthMedium": "中",
    "chat.depthHigh": "高",
    "chat.agentThinking": "Agent思考",
    "chat.compressMemory": "压缩记忆",
    "chat.compressMemoryAria": "压缩记忆，当前上下文 ${current}/${threshold}，进度 ${percent}%",
    "chat.attachImage": "附加图片或 TXT 文件",
    "chat.compressMemoryTitle": "压缩记忆 ${current}/${threshold}",
    "chat.compressContextTitle": "对话上下文与压缩进度",
    "chat.compressDirectorTitle": "导演上下文与自动压缩进度",
    "chat.compressSummaryLabel": "压缩摘要",
    "chat.compressDirectorLabel": "导演记忆",
    "chat.compressExpand": "展开",
    "chat.compressCollapse": "收起",
    "chat.compressExpandAll": "展开全部",
    "chat.compressCollapseAll": "收起全部",
    "chat.compressSegmentRange": "区间 ${range}",
    "chat.compressAction": "压缩",
    "chat.compressMetricContext": "上下文",
    "chat.compressMetricSegments": "分段记忆",
    "chat.compressMetricMessages": "消息数",
    "chat.tip1": "输入你想说的话...",
    "chat.tip2": "点击输入框左上角 ✨ 生成推荐回复",
    "chat.tip3": "Shift+Enter 换行，Enter 发送",
    "chat.tip4": "支持 Markdown 格式和代码块高亮",
    "chat.tipAt": "在输入中键入 @ 可快速调用 Agent",
  },
  "en-US": {
    "app.title": "MOYU - 模鱼空间",
    "brand.title": "MOYU",
    "brand.sidebarTitle": "MOYU",
    "brand.subtitle": "Start Moyu, start slacking!",
    "nav.create": "New Chat",
    "nav.chatList": "Chats",
    "nav.settings": "Settings",
    "nav.userRoleLibrary": "Role Presets",
    "nav.skills": "Skills",
    "skills.subtitle": "Model-driven structured questioning to help you analyze problems and organize thoughts.",
    "skills.howToUse": "How to Use",
    "skills.usageHint": "In work mode, the model will automatically decide when to use structured questioning. You can also type <code>/skill</code> to trigger it manually. The model will guide you through interactive cards, up to 5 questions, each with 3 options and custom input.",
    "skills.availableSkills": "Available Skill Scenarios",
    "skills.sceneAnalysis": "Requirement Analysis",
    "skills.sceneDesign": "Solution Design",
    "skills.sceneDebug": "Troubleshooting",
    "skills.sceneSentiment": "Sentiment Analysis",
    "skills.sceneCustom": "More scenarios determined by the model",
    "skills.tips": "Tips",
    "skills.tipManual": "Type <code>/skill</code> to trigger manually",
    "skills.tipCustom": "Choose from model-provided options or enter your own",
    "skills.tipInterrupt": "Send a normal message to exit structured questioning",
    "settings.sectionTitle": "Settings",
    "settings.sectionHint": "Choose a settings group to edit.",
    "settings.back": "Back",
    "settings.globalTab": "Global",
    "settings.assistantTab": "Assistant AI",
    "settings.apiTab": "API",
    "settings.globalTitle": "Global Settings",
    "settings.globalSubtitle": "Adjust app-wide shared settings.",
    "settings.assistantTitle": "Assistant AI",
    "settings.assistantSubtitle": "Choose the global helper model for prompt optimization and suggested input features.",
    "settings.apiTitle": "API Settings",
    "settings.apiSubtitle": "Choose an API profile, edit Host / Key, fetch models, and manage work models.",
    "settings.assistantModelTitle": "Assistant Model",
    "settings.assistantModelHint": "Pick one model from all work models to act as the global helper AI.",
    "settings.assistantModelLabel": "Assistant Model",
    "settings.assistantModelPlaceholder": "Choose an assistant model",
    "settings.assistantModelEmpty": "Select work models in API settings first",
    "settings.themeTitle": "Theme",
    "settings.themeHint": "Switch between dark and light interface theme.",
    "settings.themeLabel": "Theme",
    "settings.theme.system": "System",
    "settings.theme.dark": "Dark",
    "settings.theme.light": "Light",
    "settings.languageTitle": "Language",
    "settings.languageHint": "Control the UI language used by the app.",
    "settings.languageLabel": "Interface Language",
    "settings.locale.zh-CN": "Simplified Chinese",
    "settings.locale.en-US": "English",
    "settings.startupTitle": "Startup Page",
    "settings.startupHint": "Choose which main screen opens after a refresh.",
    "settings.initialPageLabel": "Open on Startup",
    "settings.initialPage.welcome": "Welcome Screen",
    "settings.initialPage.create": "Create New Chat",
    "settings.initialPage.lastChat": "Last Chat Session",
    "settings.globalBasicsTitle": "Basics",
    "settings.globalBasicsHint": "Set the interface language and where the app should land when it opens.",
    "settings.devTitle": "Developer",
    "settings.devHint": "Used to inspect director orchestration and session flow.",
    "settings.debugModeLabel": "Debug Mode",
    "settings.debugModeHint": "When enabled, structured debug logs will be printed to the console.",
    "settings.mobileConsoleLabel": "Mobile Debug Console",
    "settings.mobileConsoleHint": "When enabled, Eruda will load automatically on small-screen or touch devices.",
    "settings.globalDataTitle": "Backup & Restore",
    "settings.globalDataHint": "Export the full settings bundle or quickly restore your current environment from a backup.",
    "settings.globalDangerTitle": "Danger Zone",
    "settings.globalDangerHint": "Clear all local sessions and message data. This action cannot be undone.",
    "settings.sessionTab": "Session",
    "settings.sessionTitle": "Session Settings",
    "settings.sessionSubtitle": "Adjust auto-compression threshold and token display options.",
    "settings.compressThresholdLabel": "Auto-Compress Threshold",
    "settings.compressThresholdHint": "When the director context token count exceeds this value, compression triggers automatically on send.",
    "settings.showTokenDisplayLabel": "Show Token Usage",
    "settings.showTokenDisplayHint": "When disabled, token statistics will not appear below AI reply bubbles.",
    "settings.directorDispatchLabel": "Director Dispatch Only",
    "settings.directorDispatchHint": "When enabled, the director only decides who replies without telling NPCs how to act — NPCs respond freely.",
    "settings.sessionContextTitle": "Context & Compression",
    "settings.sessionContextHint": "Control when compression kicks in and how much the director should intervene.",
    "settings.markdownRenderLabel": "Markdown Render",
    "settings.markdownRenderHint": "When disabled, work mode displays plain text without Markdown rendering.",
    "settings.showLineNumbersLabel": "Code Line Numbers",
    "settings.showLineNumbersHint": "Show line numbers on the left side of code blocks.",
    "settings.sessionDisplayTitle": "Display & Reading",
    "settings.sessionDisplayHint": "Control render details, code readability, and whether token usage stays visible.",
    "settings.sessionTransferTitle": "Session Transfer",
    "settings.sessionTransferHint": "Export all sessions as backup, or import an older archive back into the current local store.",
    "settings.backupTitle": "Backup & Restore",
    "settings.backupHint": "Export all settings (including API keys) as a JSON file, or restore from a backup.",
    "settings.exportBackup": "Export Settings",
    "settings.importBackup": "Import Settings",
    "settings.importSuccess": "Settings imported successfully",
    "settings.importFailed": "Import failed: invalid file format",
    "settings.importFailedParse": "Import failed: unable to parse backup file",
    "settings.title": "API Settings",
    "settings.subtitle": "Choose an API profile, maintain Host / Key, sync models, and select work models.",
    "settings.hostLabel": "API Host",
    "settings.keyLabel": "API Key",
    "settings.configNameLabel": "Profile Name",
    "settings.configNamePlaceholder": "e.g. OpenAI Main / Test Relay",
    "settings.hostPlaceholder": "e.g. https://api.openai.com/v1",
    "settings.keyPlaceholder": "sk-...",
    "settings.save": "Save",
    "settings.fetch": "Fetch Models",
    "settings.cachedModels": "Cached Models",
    "settings.clearCache": "Clear Current Cache",
    "settings.savedConfigs": "API Profiles",
    "settings.savedConfigsHint": "Add, switch, and maintain your API profiles.",
    "settings.addConfig": "Add",
    "settings.searchLabel": "Search Models",
    "settings.searchPlaceholder": "Filter models and click to add work models",
    "settings.workModelsTitle": "Work Models",
    "settings.workModelsHint": "Click models in the cached models panel to add or remove work models.",
    "settings.clearWorkModels": "Clear",
    "settings.workModelsEmpty": "Fetch models first",
    "create.title": "Create New Chat",
    "create.subtitle": "Choose a session mode, then fill in the settings and ${entityType} config.",
    "create.editTitle": "Edit Current Session",
    "create.editSubtitle": "Modify the global prompt, director model, ${entityType} names, models, and character prompts, then save to the current session.",
    "create.newSubtitle": "Choose a session mode, then fill in the settings and ${entityType} config.",
    "create.editNavInfo": "Session Info",
    "create.editNavOverrides": "Session Interface",
    "create.editNavAdvanced": "Advanced",
    "create.exitEdit": "Exit Editing",
    "create.editSidebarTitle": "Edit Current Session",
    "create.editSidebarHint": "On desktop, use this sidebar to switch between edit sections for the current session.",
    "create.overridesSubtitle": "Adjust display settings that apply only to this session without affecting global defaults.",
    "create.overridesTitle": "Session Interface",
    "create.overridesHint": "This area is reserved for per-session tuning that should not affect global settings.",
    "create.overridesContextTitle": "Context & Dispatch",
    "create.overridesContextHint": "These changes save instantly and apply only to the current session.",
    "create.overridesDisplayTitle": "Display & Reading",
    "create.overridesDisplayHint": "Fine-tune the reading experience for this session without affecting other chats.",
    "create.overridesModelThinkingLabel": "Agent Thinking",
    "create.overridesModelThinkingHint": "Controls whether agents in this session default to sending reasoning parameters.",
    "create.overridesModelIconLabel": "Model Logo",
    "create.overridesModelIconHint": "Show or hide the model provider logo next to AI names in this session.",
    "create.overrideReset": "Use Global",
    "create.overrideUsingGlobal": "Using global default",
    "create.overrideCustomized": "Customized for this session",
    "create.overrideGlobalDefault": "Global default: ${value}",
    "create.overrideValueOn": "On",
    "create.overrideValueOff": "Off",
    "create.advancedSubtitle": "Tune generation parameters per agent for this session only.",
    "create.advancedTemperatureLabel": "Temperature",
    "create.saveBtn": "Save Session",
    "create.statusMaxNpc": "Maximum 5 ${entityType}s",
    "create.statusNpcAdded": "New ${entityType} added",
    "create.statusMinNpc": "At least ${n} ${entityType} required",
    "create.statusNpcDeleted": "${entityType} deleted",
    "create.statusCreated": "Session created",
    "create.statusSaved": "Session settings saved",
    "create.statusEditing": "Editing current session settings",
    "create.statusNotFound": "Session not found",
    "create.statusDirectorUnavailable": "Director model API profile is not available",
    "create.statusProcessing": "Processing...",
    "create.errorSelectConfig": "Select an API profile first",
    "create.statusNpcCount": "Keep ${min} to ${max} ${entityType}s",
    "create.errorSetup": "Save API Host and Key in settings first",
    "create.errorWorkModels": "Select work models in settings first",
    "create.errorGlobalPrompt": "Global prompt is required",
    "create.errorDirector": "Director model is required",
    "create.errorNpcCount": "${entityType} count must be between ${min} and ${max}",
    "create.errorNpcModel": "Each ${entityType} must have a model selected",
    "create.modelPlaceholder": "Select a model",
    "create.workModelsEmpty": "Select work models in settings first",
    "create.modeLabel": "Session Mode",
    "create.modeStory": "Story Mode",
    "create.modeStoryHint": "For scenes and character interaction, with the director steering the scene and scheduling NPCs",
    "create.modeChaos": "Chaos Mode",
    "create.modeChaosHint": "A messy social-group-chat mode where multiple AIs jump in, heckle, pile on, and talk over each other",
    "create.betaTag": "Beta",
    "create.modeWork": "Work Mode",
    "create.modeWorkHint": "For collaboration and task flow, with the director assigning order and responsibilities",
    "create.modeHint": "Choose the session mode at creation; it is permanently locked afterward and cannot be changed. Choose wisely!",
    "create.modeLockedHint": "This session mode is locked. Create a new session if you need a different mode.",
    "create.globalPromptLabel": "Global Prompt",
    "create.globalPromptPlaceholder": "Describe what this chat is for, the world setting, and what all AIs should know.",
    "create.directorLabel": "Director Model",
    "create.npcTitle": "${entityType} Setup",
    "create.npcSubtitle": "Each ${entityType} must bind to a model, and can also have its own character prompt.",
    "create.addNpc": "Add ${entityType}",
    "create.noDirectorHint": "Single ${entityType} mode does not need a director; the ${entityType} will reply directly.",
    "create.noGlobalPromptHint": "Single ${entityType} mode uses the ${entityType} Prompt as full context; no additional global settings needed.",
    "create.submit": "Create Session",
    "create.userRoleLabel": "Your Role",
    "create.userRolePlaceholder": "Optional: identity, background, speaking style",
    "create.userRoleSelect": "Select from library...",
    "roleLibrary.title": "Role Presets",
    "roleLibrary.subtitle": "Manage your role presets for quick selection when creating sessions.",
    "roleLibrary.addRole": "Add Role",
    "roleLibrary.roleName": "Role Name",
    "roleLibrary.roleDescription": "Role Description",
    "roleLibrary.roleNamePlaceholder": "e.g. Detective / Shopkeeper / Strategist",
    "roleLibrary.roleDescriptionPlaceholder": "Describe your identity, background, personality, speaking style, etc.",
    "roleLibrary.empty": "No saved roles yet. Click the button above to add one.",
    "roleLibrary.saved": "Role saved",
    "roleLibrary.deleted": "Role deleted",
    "roleLibrary.confirmDelete": "Are you sure you want to delete \"${name}\"?",
    "roleLibrary.editRole": "Edit Role",
    "roleLibrary.save": "Save Role",
    "roleLibrary.cancel": "Cancel",
    "chat.inputPlaceholder": "Type what you want to say...",
    "chat.send": "Send",
    "chat.directorThinking": "Director Thinking",
    "chat.directorDispatch": "Dispatch Only",
    "npc.unnamed": "Unnamed ${entityType}",
    "npc.noModel": "No model selected",
    "chat.globalPromptEmpty": "Not filled",
    "chat.directorEmpty": "Not selected",
    "chat.noNpcs": "No NPCs",
    "chat.metaExpand": "Expand",
    "chat.metaCollapse": "Collapse",
    "chat.menuEditSession": "Edit Session",
    "chat.menuRestart": "Restart",
    "chat.menuRename": "Rename",
    "chat.menuDelete": "Delete Chat",
    "chat.menuExport": "Export Session",
    "chat.restartedFromExisting": "Created a new blank session based on the original settings",
    "settings.exportSessionsTitle": "Export Sessions",
    "settings.exportSessionsHint": "Export all sessions as a JSON file.",
    "settings.importSessionsTitle": "Import Sessions",
    "settings.importSessionsHint": "Import one or more sessions from a JSON file.",
    "settings.importSessionsSuccess": "Sessions imported successfully",
    "settings.importSessionsFailed": "Import failed: invalid file format",
    "settings.importSessionsPartial": "Import complete, ${n} session(s) skipped due to invalid data",
    "drop.overlayGlobal": "Release to import settings backup",
    "drop.overlaySession": "Release to import session files",
    "drop.overlayAuto": "Release to import file",
    "drop.overlayChatAttachment": "Release to attach images or TXT files",
    "npc.nameLabel": "${entityType} Name",
    "npc.namePlaceholder": "e.g. Detective / Shopkeeper / Strategist",
    "npc.modelLabel": "Model",
    "npc.promptLabel": "${entityType} Prompt",
    "npc.promptPlaceholder": "Optional: tone, secrets, goals, speaking style.",
    "npc.footer": "All ${entityType}s can see the global prompt and full chat history.",
    "npc.remove": "Remove",
    "chat.currentSession": "Current Chat",
    "chat.emptySessions": "No chats yet",
    "chat.noActiveSession": "No active chat yet",
    "chat.generatingTitle": "Generating title...",
    "chat.systemSpeaker": "System",
    "chat.systemNoticeCreated": "Session created",
    "chat.globalPromptLabel": "Global Setting",
    "chat.readyAfterCreate": "Create a chat to start talking",
    "chat.thinkingLabel": "Thinking",
    "chat.welcomeIntro": "A multi-AI theater and character dialogue playground.",
    "chat.welcomeHint": "Set up your API and work models on the left, then create a chat to begin.",
    "chat.regenerate": "Regenerate",
    "chat.regenerateHint": "Regenerate from your last message",
    "chat.copy": "Copy",
    "chat.copied": "Copied",
    "chat.stopped": "Stopped",
    "chat.stoppedHint": "User stopped the generation",

    "debug.scope.director": "Director",
    "debug.scope.turn": "Turn",
    "debug.scope.compress": "Compress",
    "debug.scope.npc": "NPC",
    "debug.scope.settings": "Settings",
    "debug.scope.bootstrap": "Bootstrap",
    "debug.scope.stripThinking": "Strip Thinking",
    "debug.msg.requestAttempt": "Request attempt",
    "debug.msg.rawResponse": "Raw response",
    "debug.msg.retry": "Retrying",
    "debug.msg.failed": "Failed",
    "debug.msg.started": "Started",
    "debug.msg.finished": "Finished",
    "debug.msg.aborted": "Aborted",
    "debug.msg.toolbarIconPointerdown": "Toolbar icon pointerdown",
    "debug.msg.toolbarIconClick": "Toolbar icon click",
    "debug.msg.popoverClosedOutside": "Popover closed by outside click",
    "debug.msg.regenerate": "Regenerate from user message",
    "debug.msg.userMessageSubmitted": "User message submitted",
    "debug.msg.turnFailed": "Turn failed",
    "debug.msg.directorTurnStarted": "Director turn started",
    "debug.msg.directiveAccepted": "Directive accepted",
    "debug.msg.transientNpcsUpdated": "Transient NPCs updated",
    "debug.msg.respondersResolved": "Responders resolved",
    "debug.msg.npcRepliesCompleted": "NPC replies completed",
    "debug.msg.rawResponseReceived": "Raw response received",
    "debug.msg.invalidResponseRetrying": "Invalid response, retrying",
    "debug.msg.repairResponseAccepted": "Repair response accepted",
    "debug.msg.repairResponseFailed": "Repair response failed",
    "debug.msg.repairAttempt": "Repair attempt",
    "debug.msg.repairRawResponse": "Repair raw response received",
    "debug.msg.compressionRequested": "Compression requested",
    "debug.msg.compressionAborted": "Compression aborted before start",
    "debug.msg.compressionStarted": "Compression started",
    "debug.msg.compressionFinished": "Compression finished",
    "debug.msg.compressionFailed": "Compression failed",
    "debug.msg.popoverMountSkipped": "Popover mount skipped",
    "debug.msg.popoverMounted": "Popover mounted",
    "debug.msg.popoverRenderSkipped": "Popover render skipped",
    "debug.msg.popoverRendered": "Popover rendered",
    "debug.msg.popoverActionPointerdown": "Popover action pointerdown",
    "debug.msg.popoverActionClick": "Popover action click",
    "debug.msg.popoverActionBound": "Popover action bound",
    "debug.msg.popoverActionMissing": "Popover action missing after render",
    "debug.msg.strippedRepeatedBlocks": "Stripped repeated blocks",
    "debug.msg.debugModeToggled": "Debug mode toggled",
    "debug.msg.mobileDebugConsole": "Mobile debug console enabled",
    "debug.msg.npcRetry": "${speaker} first call returned empty, retrying...",

    "loading.start": "Start Moyu",
    "settings.clearAllData": "Clear All Messages",
    "settings.clearAllDataConfirm": "Clear all sessions and message data? This cannot be undone!",
    "settings.clearAllDataConfirm2": "Confirm again: all chat records will be permanently deleted.",
    "settings.clearAllDataSuccess": "All session messages cleared",
    "settings.clearAllDataFailed": "Clear failed: ${message}",
    "chat.statusReady": "Ready",
    "chat.statusProcessing": "Processing...",
    "chat.suggestHintNoAssistant": "Set an assistant model in Settings first",
    "chat.suggestHintNeedReply": "Wait for an AI reply before requesting suggestions",
    "chat.thinkingSettings": "Thinking",
    "chat.deepThinking": "Deep Thinking",
    "chat.depthLow": "Low",
    "chat.depthMedium": "Med",
    "chat.depthHigh": "High",
    "chat.agentThinking": "Agent Thinking",
    "chat.compressMemory": "Compress Memory",
    "chat.compressMemoryAria": "Compress memory, ${current}/${threshold}, ${percent}%",
    "chat.attachImage": "Attach image or TXT file",
    "chat.compressMemoryTitle": "Compress memory ${current}/${threshold}",
    "chat.compressContextTitle": "Context & Compression Progress",
    "chat.compressDirectorTitle": "Director Context & Compression Progress",
    "chat.compressSummaryLabel": "Summary",
    "chat.compressDirectorLabel": "Director Memory",
    "chat.compressExpand": "Expand",
    "chat.compressCollapse": "Collapse",
    "chat.compressExpandAll": "Expand All",
    "chat.compressCollapseAll": "Collapse All",
    "chat.compressSegmentRange": "Range ${range}",
    "chat.compressAction": "Compress",
    "chat.compressMetricContext": "Context",
    "chat.compressMetricSegments": "Segments",
    "chat.compressMetricMessages": "Messages",
    "chat.tip1": "Type what you want to say...",
    "chat.tip2": "Click ✨ above-left for suggested replies",
    "chat.tip3": "Shift+Enter for new line, Enter to send",
    "chat.tip4": "Markdown and code highlighting supported",
    "chat.tipAt": "Type @ to mention an Agent",
  },
};

const STORY_DIRECTOR_SYSTEM_PROMPT = [
  "你是导演调度器。你的唯一输出必须是一个 JSON 对象。",
  "禁止输出自然语言、解释、markdown、代码块、旁白前缀。",
  "输出格式固定：",
  '{"narration":"简短场景描写或空字符串","responders":["先说话的NPC","后说话的NPC"],"spawn_npcs":[{"name":"临时NPC名","prompt":"一句话角色描述"}],"npc_instructions":{"NPC名":"导演给这个NPC的额外要求"}}',
  "",
  "你会看到：全局设定、固定 NPC 列表、场内 NPC 列表、摘要或历史。",
  "HISTORY/RECENT_HISTORY 中：{user} 是用户，{npc} 是 NPC，{narration} 是旁白。",
  "",
  "硬规则：",
  "1. 用户最新消息点名了谁，谁必须进 responders。昵称、简称、部分匹配也算。",
  "2. 如果用户明显是在接上一轮某个 NPC 的话，即使没点名，该 NPC 也必须进 responders。",
  "3. 如果用户没指向任何 NPC，responders 可以为空数组。",
  "4. responders 里出现了不在固定 NPC 列表中的名字，它必须同时出现在 spawn_npcs 中。",
  "5. responders 数组本身就是发言顺序，越靠前越先说。顺序必须合理，不能机械按固定名单顺序排。",
  "6. 用户口中的称呼、身份词、职业词、场景角色词，必须优先映射到已有固定 NPC 或场内 NPC，而不是轻易新建人。",
  "7. 只要已有 NPC 的名字、角色描述、身份设定、职责定位能合理承接这个称呼，就必须直接使用那个已有 NPC 的真实名字写入 responders。",
  "8. spawn_npcs 只能用于场内确实没有合适现成人物可接这个称呼的情况。",
  "",
  "顺序判断优先级：",
  "- 被用户直接点名、追问、质疑的人优先。",
  "- 上一轮刚和用户对话、现在最像被接话的人优先。",
  "- 更贴近当前动作、事件中心、身份更强势的人可以优先。",
  "- 其他 NPC 用来补充、附和、反驳、收尾。",
  "",
  "narration 规则：",
  "- 只写一句很短的动作/环境/气氛描写，也可以直接写空字符串。",
  "- 绝对不能写 NPC 台词。",
  "- 如果 responder 已经要亲自开口，narration 只写极简动作，不要提前剧透他说什么。",
  "- 如果与已有旁白高度重复，优先写空字符串。",
  "",
  "spawn_npcs 规则：",
  "- 只在确实需要临时 NPC 回话时生成。",
  "- 在生成前，先检查固定 NPC 与场内 NPC 的名字、角色描述、职责、身份、立场是否已经能承接用户当前称呼。",
  "- 只要已有 NPC 可以合理承接，就不要新生一个同职能、同身份、同场景位置的人。",
  '- 格式固定为 [{"name":"名字","prompt":"一句话角色描述"}]。',
  "- prompt 简短，用中文。",
  "",
  "=== npc_instructions 规则（重要） ===",
  "npc_instructions 是一个对象，key 是 NPC 名字（必须在 responders 或 spawn_npcs 中出现），value 是你作为导演对那个 NPC 的具体要求。",
  "用途示例：",
  '- 用户说"给我简单说下" → 导演可以要求该 NPC "控制在 50 字以内，简洁回答"',
  '- 用户提问某个话题 → 导演可以要求对应 NPC "侧重解释 X 方面，语气要耐心"',
  '- 用户要求激烈争吵 → 导演可以要求对应 NPC "语气要愤怒，多质问对方"',
  '- 用户不想太长 → 导演要求所有 NPC "每句话控制在 30 字以内"',
  "- 如果不需对某个 NPC 提额外要求，可以不写该 NPC 的 key，或 npc_instructions 设为 {}。",
  "",
  "正确示例：",
  '用户: "小翠，给我倒杯茶，简短说" → {"narration":"小翠应了一声，提起茶壶。","responders":["小翠"],"spawn_npcs":[],"npc_instructions":{"小翠":"控制在15字以内，简洁回应"}}',
  '用户: "老板，你这菜多少钱？给我算便宜点"；固定 NPC 有"老板" → {"narration":"柜台后有人抬了下眼。","responders":["老板"],"spawn_npcs":[],"npc_instructions":{"老板":"语气要精明，带点生意人的算计，回应价格话题"}}',
  '用户: "你们俩都说说看法" → {"narration":"","responders":["春桃","小翠"],"spawn_npcs":[],"npc_instructions":{"春桃":"侧重分析利弊，理性","小翠":"从感情角度出发，感性"}}',
  "",
  "最后再提醒一次：只输出 JSON 对象本身，一行。"
].join("\n");

const WORK_DIRECTOR_SYSTEM_PROMPT = [
  "你是工作会话的导演调度器。你的唯一输出必须是一个 JSON 对象。",
  "禁止输出自然语言、解释、markdown、代码块、旁白前缀。",
  "输出格式固定：",
  '{"narration":"","responders":["先说话的NPC","后说话的NPC"],"spawn_npcs":[{"name":"临时NPC名","prompt":"一句话角色描述"}],"npc_instructions":{"NPC名":"给这个NPC的简短执行要求"}}',
  "",
  "你的任务很简单：根据用户最新需求，安排这一轮由谁回答、顺序怎样、每个 NPC 负责什么。",
  "重点是调度清楚、分工明确、响应直接，不要写剧情导演式的复杂规则或氛围化指令。",
  "",
  "硬规则：",
  "1. responders 只列本轮需要回答的 NPC，顺序就是发言顺序。",
  "2. 如果用户点名了某个 NPC，该 NPC 必须进入 responders。",
  "3. 如果用户要求多人协作，可以安排多个 NPC，顺序按任务流转来排。",
  "4. 优先复用已有固定 NPC 或场内 NPC，不要随便新建临时 NPC。",
  "5. spawn_npcs 只在现有 NPC 确实无法承接任务时才使用。",
  "6. npc_instructions 只写简短执行要求，例如“先给结论，再补两条理由”或“负责指出风险”。",
  "7. narration 默认写空字符串；除非确实需要一句极短过渡，否则不要写。",
  "8. 只输出合法 JSON，不要附加任何说明。",
].join("\n");

function getDirectorSystemPrompt(session) {
  return session?.mode === SESSION_MODE_WORK
    ? WORK_DIRECTOR_SYSTEM_PROMPT
    : STORY_DIRECTOR_SYSTEM_PROMPT;
}

const SESSION_MODE_STORY = "story";
const SESSION_MODE_CHAOS = "chaos";
const SESSION_MODE_WORK = "work";

const MODEL_ICON_CDN =
  "./vendor/lobehub-icons/1.90.0/icons/";

const MODEL_PROVIDERS = [
  { id: "openai", match: /gpt|openai|o1|o3|o4/i, icon: `${MODEL_ICON_CDN}openai.svg` },
  { id: "claude", match: /claude|anthropic/i, icon: `${MODEL_ICON_CDN}claude-color.svg` },
  { id: "gemini", match: /gemini|google/i, icon: `${MODEL_ICON_CDN}gemini-color.svg` },
  { id: "grok", match: /grok|xai/i, icon: `${MODEL_ICON_CDN}grok.svg` },
  { id: "groq", match: /groq/i, icon: `${MODEL_ICON_CDN}groq.svg` },
  { id: "deepseek", match: /deepseek/i, icon: `${MODEL_ICON_CDN}deepseek-color.svg` },
  { id: "qwen", match: /qwen|qwq|tongyi|dashscope/i, icon: `${MODEL_ICON_CDN}qwen-color.svg` },
  { id: "kimi", match: /kimi|moonshot/i, icon: `${MODEL_ICON_CDN}kimi-color.svg` },
  { id: "doubao", match: /doubao|volc|ark/i, icon: `${MODEL_ICON_CDN}doubao-color.svg` },
  { id: "zhipu", match: /zhipu|glm|chatglm/i, icon: `${MODEL_ICON_CDN}zhipu-color.svg` },
  { id: "hunyuan", match: /hunyuan|tencent/i, icon: `${MODEL_ICON_CDN}hunyuan-color.svg` },
  { id: "baidu", match: /ernie|wenxin|baidu/i, icon: `${MODEL_ICON_CDN}baidu-color.svg` },
  { id: "minimax", match: /minimax|abab/i, icon: `${MODEL_ICON_CDN}minimax-color.svg` },
  { id: "yi", match: /yi|01-ai/i, icon: `${MODEL_ICON_CDN}yi-color.svg` },
  { id: "meta", match: /llama|meta/i, icon: `${MODEL_ICON_CDN}meta-color.svg` },
  { id: "mistral", match: /mistral|mixtral/i, icon: `${MODEL_ICON_CDN}mistral-color.svg` },
  { id: "cohere", match: /cohere/i, icon: `${MODEL_ICON_CDN}cohere-color.svg` },
  { id: "perplexity", match: /perplexity|sonar/i, icon: `${MODEL_ICON_CDN}perplexity-color.svg` },
  { id: "ollama", match: /ollama/i, icon: `${MODEL_ICON_CDN}ollama.svg` },
  { id: "huggingface", match: /huggingface|hf/i, icon: `${MODEL_ICON_CDN}huggingface-color.svg` },
  { id: "openrouter", match: /openrouter/i, icon: `${MODEL_ICON_CDN}openrouter.svg` },
];

function detectModelProvider(modelName) {
  if (!modelName || typeof modelName !== "string") return null;
  return MODEL_PROVIDERS.find((p) => p.match.test(modelName)) || null;
}
