const STORAGE_KEYS = {
  settings: "moyu-settings",
  modelCache: "moyu-model-cache",
  currentSession: "moyu-current-session",
  sessions: "moyu-sessions",
  currentSessionId: "moyu-current-session-id",
  locale: "moyu-locale",
  sidebarCollapsed: "moyu-sidebar-collapsed",
};

const i18n = {
  "zh-CN": {
    "app.title": "MOYU - 模鱼空间",
    "brand.title": "MOYU-模鱼",
    "brand.sidebarTitle": "MOYU",
    "brand.subtitle": "开始模鱼，开始摸鱼！",
    "nav.create": "创建聊天",
    "nav.chatList": "聊天列表",
    "nav.settings": "设置",
    "settings.sectionTitle": "设置分类",
    "settings.sectionHint": "先选择要调整的设置分组。",
    "settings.globalTab": "全局设置",
    "settings.assistantTab": "辅助 AI",
    "settings.apiTab": "接口设置",
    "settings.globalTitle": "全局设置",
    "settings.globalSubtitle": "调整整个应用通用的设置项。",
    "settings.assistantTitle": "辅助 AI",
    "settings.assistantSubtitle": "配置全局辅助模型，供设定优化、推荐输入等能力使用。",
    "settings.apiTitle": "接口设置",
    "settings.apiSubtitle": "选择一个接口，修改 Host / Key，获取该接口模型列表，并维护工作模型。",
    "settings.assistantModelTitle": "辅助模型",
    "settings.assistantModelHint": "从所有工作模型里选一个，作为全局辅助 AI 默认模型。",
    "settings.assistantModelLabel": "辅助模型",
    "settings.assistantModelPlaceholder": "请选择辅助模型",
    "settings.assistantModelEmpty": "请先在接口设置中勾选工作模型",
    "settings.languageTitle": "语言设置",
    "settings.languageHint": "控制整个应用当前使用的界面语言。",
    "settings.languageLabel": "界面语言",
    "settings.locale.zh-CN": "简体中文",
    "settings.locale.en-US": "English",
    "settings.startupTitle": "初始页面",
    "settings.startupHint": "控制刷新页面后默认进入哪一种主界面。",
    "settings.initialPageLabel": "启动时打开",
    "settings.initialPage.welcome": "默认欢迎页",
    "settings.initialPage.create": "创建新聊天",
    "settings.initialPage.lastChat": "最后一次聊天",
    "settings.devTitle": "开发者选项",
    "settings.devHint": "用于排查导演调度和会话流程问题。",
    "settings.debugModeLabel": "调试模式",
    "settings.debugModeHint": "开启后会在 console 中输出结构化调试日志。",
    "settings.mobileConsoleLabel": "移动端调试控制台",
    "settings.mobileConsoleHint": "开启后会在小屏或触屏设备自动加载 Eruda 调试工具。",
    "settings.sessionTab": "会话设置",
    "settings.sessionTitle": "会话设置",
    "settings.sessionSubtitle": "调整自动压缩阈值与 Token 显示等会话相关选项。",
    "settings.compressThresholdLabel": "自动压缩阈值",
    "settings.compressThresholdHint": "导演上下文 Token 数超过此值后，在发送消息时自动触发压缩。",
    "settings.showTokenDisplayLabel": "显示 Token 用量",
    "settings.showTokenDisplayHint": "关闭后 AI 回复气泡底部将不再显示 Token 统计信息。",
    "settings.directorDispatchLabel": "导演纯调度",
    "settings.directorDispatchHint": "开启后导演只决定谁回答，不指挥 NPC 怎么演，NPC 自由发挥。",
    "settings.markdownRenderLabel": "Markdown 渲染",
    "settings.markdownRenderHint": "关闭后工作模式将使用纯文本显示，不渲染 Markdown。",
    "settings.backupTitle": "设置备份",
    "settings.backupHint": "导出所有设置（含 API Key）为 JSON 文件，或从备份文件恢复。",
    "settings.exportBackup": "导出设置备份",
    "settings.importBackup": "导入设置备份",
    "settings.importSuccess": "设置已成功导入",
    "settings.importFailed": "导入失败：文件格式不正确",
    "settings.importFailedParse": "导入失败：无法解析备份文件",
    "settings.title": "接口设置",
    "settings.subtitle": "选择接口、维护 Host / Key、同步模型列表，并勾选工作模型。",
    "settings.hostLabel": "API Host",
    "settings.keyLabel": "API Key",
    "settings.configNameLabel": "接口名称",
    "settings.configNamePlaceholder": "例如 OpenAI 主账号 / 临时中转站",
    "settings.hostPlaceholder": "例如 https://api.openai.com/v1",
    "settings.keyPlaceholder": "sk-...",
    "settings.save": "保存设置",
    "settings.fetch": "获取模型列表",
    "settings.cachedModels": "缓存模型",
    "settings.clearCache": "清空当前缓存",
    "settings.savedConfigs": "接口列表",
    "settings.savedConfigsHint": "新增、切换并维护你的接口配置。",
    "settings.addConfig": "新增",
    "settings.searchLabel": "搜索模型",
    "settings.searchPlaceholder": "输入模型名筛选并点击选择工作模型",
    "settings.workModelsTitle": "工作模型",
    "settings.workModelsHint": "在右侧缓存模型区点击即可加入或移出工作模型。",
    "settings.clearWorkModels": "清空",
    "settings.workModelsEmpty": "请先获取模型列表",
    "create.title": "创建新聊天",
    "create.subtitle": "先选择会话模式，再填写设定和 ${entityType} 配置。",
    "create.editTitle": "编辑当前会话",
    "create.editSubtitle": "修改全局设定、导演模型、${entityType} 名称、模型与角色 Prompt，然后保存到当前会话。",
    "create.newSubtitle": "先选择会话模式，再填写设定和 ${entityType} 配置。",
    "create.saveBtn": "保存会话",
    "create.statusMaxNpc": "最多添加 5 个 ${entityType}",
    "create.statusNpcAdded": "已添加新的 ${entityType}",
    "create.statusMinNpc": "至少保留 ${n} 个 ${entityType}",
    "create.statusNpcDeleted": "${entityType} 已删除",
    "create.statusCreated": "会话已创建",
    "create.statusSaved": "会话设定已保存",
    "create.statusEditing": "正在编辑当前会话设定",
    "create.statusNotFound": "要编辑的会话不存在",
    "create.statusDirectorUnavailable": "导演模型所属接口不可用",
    "create.statusProcessing": "正在处理中...",
    "create.errorSelectConfig": "请先选择一个接口",
    "create.statusNpcCount": "请保持 ${min} 到 ${max} 个 ${entityType}",
    "create.errorSetup": "请先在设置中保存 API Host 和 Key",
    "create.errorWorkModels": "请先在设置中勾选工作模型",
    "create.errorGlobalPrompt": "请填写全局 Prompt",
    "create.errorDirector": "请选择导演模型",
    "create.errorNpcCount": "${entityType} 数量需要在 ${min} 到 ${max} 个之间",
    "create.errorNpcModel": "每个 ${entityType} 都必须选择模型",
    "create.modelPlaceholder": "请选择模型",
    "create.workModelsEmpty": "请先在设置中勾选工作模型",
    "create.modeLabel": "会话模式",
    "create.modeStory": "创作模式",
    "create.modeStoryHint": "面向剧情与角色互动，导演负责推进场景并调度 NPC",
    "create.modeWork": "工作模式",
    "create.modeWorkHint": "面向协作分工，导演负责安排回答顺序和任务分配",
    "create.modeHint": "创建时选择会话模式；创建后模式会锁定。两种模式都由导演调度，只是调度目标不同。",
    "create.modeLockedHint": "当前会话模式已锁定；如需切换模式，请新建会话。",
    "create.globalPromptLabel": "全局 Prompt",
    "create.globalPromptPlaceholder": "描述这个聊天是做什么的、世界观是什么、所有 AI 都应该知道什么。",
    "create.directorLabel": "导演模型",
    "create.npcTitle": "${entityType} 配置",
    "create.npcSubtitle": "每个 ${entityType} 必须绑定一个模型，也可以填写独立人物 Prompt。",
    "create.addNpc": "添加 ${entityType}",
    "create.noDirectorHint": "单 ${entityType} 模式无需导演调度，${entityType} 将直接回复。",
    "create.noGlobalPromptHint": "单 ${entityType} 模式将 ${entityType} Prompt 作为全部上下文，无需额外全局设定。",
    "create.submit": "创建会话",
    "chat.inputPlaceholder": "输入你想说的话...",
    "chat.send": "发送",
    "chat.directorThinking": "导演思考",
    "chat.directorDispatch": "纯调度",
    "npc.unnamed": "未命名 ${entityType}",
    "npc.noModel": "未选择模型",
    "chat.globalPromptEmpty": "未填写",
    "chat.directorEmpty": "未选择",
    "chat.noNpcs": "暂无 NPC",
    "chat.metaExpand": "展开",
    "chat.metaCollapse": "收起",
    "chat.menuEditSession": "编辑会话",
    "chat.menuRestart": "重新开始",
    "chat.menuRename": "重命名",
    "chat.menuDelete": "删除聊天",
    "chat.menuExport": "导出会话",
    "chat.restartedFromExisting": "已基于原会话设定创建新的空白会话",
    "settings.exportSessionsTitle": "导出会话",
    "settings.exportSessionsHint": "将所有会话导出为 JSON 文件。",
    "settings.importSessionsTitle": "导入会话",
    "settings.importSessionsHint": "从 JSON 文件导入一个或多个会话。",
    "settings.importSessionsSuccess": "会话导入成功",
    "settings.importSessionsFailed": "导入失败：文件格式不正确",
    "settings.importSessionsPartial": "导入完成，其中 ${n} 个会话因数据异常被跳过",
    "drop.overlayGlobal": "松开以导入设置备份",
    "drop.overlaySession": "松开以导入会话文件",
    "drop.overlayAuto": "松开以导入文件",
    "npc.nameLabel": "${entityType} 名称",
    "npc.namePlaceholder": "例如：侦探 / 店主 / 军师",
    "npc.modelLabel": "模型",
    "npc.promptLabel": "${entityType} Prompt",
    "npc.promptPlaceholder": "可选：人物口吻、秘密、目标、说话风格。",
    "npc.footer": "所有 ${entityType} 都会看到全局 Prompt 和完整聊天记录。",
    "npc.remove": "删除",
    "chat.currentSession": "当前会话",
    "chat.emptySessions": "还没有会话",
    "chat.noActiveSession": "还没有活动会话",
    "chat.generatingTitle": "生成标题中...",
    "chat.systemSpeaker": "系统",
    "chat.systemNoticeCreated": "会话已创建",
    "chat.globalPromptLabel": "全局设定",
    "chat.readyAfterCreate": "创建会话后即可聊天",
    "chat.welcomeIntro": "一个多 AI 剧场与角色对话实验场。",
    "chat.welcomeHint": "先在左侧设置接口与工作模型，再创建聊天开始模鱼。",
    "chat.regenerate": "重新生成",
    "chat.regenerateHint": "从您的最后一条消息重新生成",
    "chat.copy": "复制",
    "chat.copied": "已复制",
  },
  "en-US": {
    "app.title": "MOYU - 模鱼空间",
    "brand.title": "MOYU",
    "brand.sidebarTitle": "MOYU",
    "brand.subtitle": "Start Moyu, start slacking!",
    "nav.create": "New Chat",
    "nav.chatList": "Chats",
    "nav.settings": "Settings",
    "settings.sectionTitle": "Settings",
    "settings.sectionHint": "Choose a settings group to edit.",
    "settings.globalTab": "Global",
    "settings.assistantTab": "Assistant AI",
    "settings.apiTab": "API",
    "settings.globalTitle": "Global Settings",
    "settings.globalSubtitle": "Adjust app-wide shared settings.",
    "settings.assistantTitle": "Assistant AI",
    "settings.assistantSubtitle": "Choose the global helper model for prompt optimization and suggested input features.",
    "settings.apiTitle": "API Settings",
    "settings.apiSubtitle": "Choose an API profile, edit Host / Key, fetch models, and manage work models.",
    "settings.assistantModelTitle": "Assistant Model",
    "settings.assistantModelHint": "Pick one model from all work models to act as the global helper AI.",
    "settings.assistantModelLabel": "Assistant Model",
    "settings.assistantModelPlaceholder": "Choose an assistant model",
    "settings.assistantModelEmpty": "Select work models in API settings first",
    "settings.languageTitle": "Language",
    "settings.languageHint": "Control the UI language used by the app.",
    "settings.languageLabel": "Interface Language",
    "settings.locale.zh-CN": "Simplified Chinese",
    "settings.locale.en-US": "English",
    "settings.startupTitle": "Startup Page",
    "settings.startupHint": "Choose which main screen opens after a refresh.",
    "settings.initialPageLabel": "Open on Startup",
    "settings.initialPage.welcome": "Welcome Screen",
    "settings.initialPage.create": "Create New Chat",
    "settings.initialPage.lastChat": "Last Chat Session",
    "settings.devTitle": "Developer",
    "settings.devHint": "Used to inspect director orchestration and session flow.",
    "settings.debugModeLabel": "Debug Mode",
    "settings.debugModeHint": "When enabled, structured debug logs will be printed to the console.",
    "settings.mobileConsoleLabel": "Mobile Debug Console",
    "settings.mobileConsoleHint": "When enabled, Eruda will load automatically on small-screen or touch devices.",
    "settings.sessionTab": "Session",
    "settings.sessionTitle": "Session Settings",
    "settings.sessionSubtitle": "Adjust auto-compression threshold and token display options.",
    "settings.compressThresholdLabel": "Auto-Compress Threshold",
    "settings.compressThresholdHint": "When the director context token count exceeds this value, compression triggers automatically on send.",
    "settings.showTokenDisplayLabel": "Show Token Usage",
    "settings.showTokenDisplayHint": "When disabled, token statistics will not appear below AI reply bubbles.",
    "settings.markdownRenderLabel": "Markdown Render",
    "settings.markdownRenderHint": "When disabled, work mode displays plain text without Markdown rendering.",
    "settings.backupTitle": "Backup & Restore",
    "settings.backupHint": "Export all settings (including API keys) as a JSON file, or restore from a backup.",
    "settings.exportBackup": "Export Settings",
    "settings.importBackup": "Import Settings",
    "settings.importSuccess": "Settings imported successfully",
    "settings.importFailed": "Import failed: invalid file format",
    "settings.importFailedParse": "Import failed: unable to parse backup file",
    "settings.title": "API Settings",
    "settings.subtitle": "Choose an API profile, maintain Host / Key, sync models, and select work models.",
    "settings.hostLabel": "API Host",
    "settings.keyLabel": "API Key",
    "settings.configNameLabel": "Profile Name",
    "settings.configNamePlaceholder": "e.g. OpenAI Main / Test Relay",
    "settings.hostPlaceholder": "e.g. https://api.openai.com/v1",
    "settings.keyPlaceholder": "sk-...",
    "settings.save": "Save",
    "settings.fetch": "Fetch Models",
    "settings.cachedModels": "Cached Models",
    "settings.clearCache": "Clear Current Cache",
    "settings.savedConfigs": "API Profiles",
    "settings.savedConfigsHint": "Add, switch, and maintain your API profiles.",
    "settings.addConfig": "Add",
    "settings.searchLabel": "Search Models",
    "settings.searchPlaceholder": "Filter models and click to add work models",
    "settings.workModelsTitle": "Work Models",
    "settings.workModelsHint": "Click models in the cached models panel to add or remove work models.",
    "settings.clearWorkModels": "Clear",
    "settings.workModelsEmpty": "Fetch models first",
    "create.title": "Create New Chat",
    "create.subtitle": "Choose a session mode, then fill in the settings and ${entityType} config.",
    "create.editTitle": "Edit Current Session",
    "create.editSubtitle": "Modify the global prompt, director model, ${entityType} names, models, and character prompts, then save to the current session.",
    "create.newSubtitle": "Choose a session mode, then fill in the settings and ${entityType} config.",
    "create.saveBtn": "Save Session",
    "create.statusMaxNpc": "Maximum 5 ${entityType}s",
    "create.statusNpcAdded": "New ${entityType} added",
    "create.statusMinNpc": "At least ${n} ${entityType} required",
    "create.statusNpcDeleted": "${entityType} deleted",
    "create.statusCreated": "Session created",
    "create.statusSaved": "Session settings saved",
    "create.statusEditing": "Editing current session settings",
    "create.statusNotFound": "Session not found",
    "create.statusDirectorUnavailable": "Director model API profile is not available",
    "create.statusProcessing": "Processing...",
    "create.errorSelectConfig": "Select an API profile first",
    "create.statusNpcCount": "Keep ${min} to ${max} ${entityType}s",
    "create.errorSetup": "Save API Host and Key in settings first",
    "create.errorWorkModels": "Select work models in settings first",
    "create.errorGlobalPrompt": "Global prompt is required",
    "create.errorDirector": "Director model is required",
    "create.errorNpcCount": "${entityType} count must be between ${min} and ${max}",
    "create.errorNpcModel": "Each ${entityType} must have a model selected",
    "create.modelPlaceholder": "Select a model",
    "create.workModelsEmpty": "Select work models in settings first",
    "create.modeLabel": "Session Mode",
    "create.modeStory": "Story Mode",
    "create.modeStoryHint": "For scenes and character interaction, with the director steering the scene and scheduling NPCs",
    "create.modeWork": "Work Mode",
    "create.modeWorkHint": "For collaboration and task flow, with the director assigning order and responsibilities",
    "create.modeHint": "Choose the session mode when creating the session; it becomes locked afterward. Both modes are director-orchestrated, but with different goals.",
    "create.modeLockedHint": "This session mode is locked. Create a new session if you need a different mode.",
    "create.globalPromptLabel": "Global Prompt",
    "create.globalPromptPlaceholder": "Describe what this chat is for, the world setting, and what all AIs should know.",
    "create.directorLabel": "Director Model",
    "create.npcTitle": "${entityType} Setup",
    "create.npcSubtitle": "Each ${entityType} must bind to a model, and can also have its own character prompt.",
    "create.addNpc": "Add ${entityType}",
    "create.noDirectorHint": "Single ${entityType} mode does not need a director; the ${entityType} will reply directly.",
    "create.noGlobalPromptHint": "Single ${entityType} mode uses the ${entityType} Prompt as full context; no additional global settings needed.",
    "create.submit": "Create Session",
    "chat.inputPlaceholder": "Type what you want to say...",
    "chat.send": "Send",
    "chat.directorThinking": "Director Thinking",
    "chat.directorDispatch": "Dispatch Only",
    "npc.unnamed": "Unnamed ${entityType}",
    "npc.noModel": "No model selected",
    "chat.globalPromptEmpty": "Not filled",
    "chat.directorEmpty": "Not selected",
    "chat.noNpcs": "No NPCs",
    "chat.metaExpand": "Expand",
    "chat.metaCollapse": "Collapse",
    "chat.menuEditSession": "Edit Session",
    "chat.menuRestart": "Restart",
    "chat.menuRename": "Rename",
    "chat.menuDelete": "Delete Chat",
    "chat.menuExport": "Export Session",
    "chat.restartedFromExisting": "Created a new blank session based on the original settings",
    "settings.exportSessionsTitle": "Export Sessions",
    "settings.exportSessionsHint": "Export all sessions as a JSON file.",
    "settings.importSessionsTitle": "Import Sessions",
    "settings.importSessionsHint": "Import one or more sessions from a JSON file.",
    "settings.importSessionsSuccess": "Sessions imported successfully",
    "settings.importSessionsFailed": "Import failed: invalid file format",
    "settings.importSessionsPartial": "Import complete, ${n} session(s) skipped due to invalid data",
    "drop.overlayGlobal": "Release to import settings backup",
    "drop.overlaySession": "Release to import session files",
    "drop.overlayAuto": "Release to import file",
    "npc.nameLabel": "${entityType} Name",
    "npc.namePlaceholder": "e.g. Detective / Shopkeeper / Strategist",
    "npc.modelLabel": "Model",
    "npc.promptLabel": "${entityType} Prompt",
    "npc.promptPlaceholder": "Optional: tone, secrets, goals, speaking style.",
    "npc.footer": "All ${entityType}s can see the global prompt and full chat history.",
    "npc.remove": "Remove",
    "chat.currentSession": "Current Chat",
    "chat.emptySessions": "No chats yet",
    "chat.noActiveSession": "No active chat yet",
    "chat.generatingTitle": "Generating title...",
    "chat.systemSpeaker": "System",
    "chat.systemNoticeCreated": "Session created",
    "chat.globalPromptLabel": "Global Setting",
    "chat.readyAfterCreate": "Create a chat to start talking",
    "chat.welcomeIntro": "A multi-AI theater and character dialogue playground.",
    "chat.welcomeHint": "Set up your API and work models on the left, then create a chat to begin.",
    "chat.regenerate": "Regenerate",
    "chat.regenerateHint": "Regenerate from your last message",
    "chat.copy": "Copy",
    "chat.copied": "Copied",
  },
};

const STORY_DIRECTOR_SYSTEM_PROMPT = [
  "你是导演调度器。你的唯一输出必须是一个 JSON 对象。",
  "禁止输出自然语言、解释、markdown、代码块、旁白前缀。",
  "输出格式固定：",
  '{"narration":"简短场景描写或空字符串","responders":["先说话的NPC","后说话的NPC"],"spawn_npcs":[{"name":"临时NPC名","prompt":"一句话角色描述"}],"npc_instructions":{"NPC名":"导演给这个NPC的额外要求"}}',
  "",
  "你会看到：全局设定、固定 NPC 列表、场内 NPC 列表、摘要或历史。",
  "HISTORY/RECENT_HISTORY 中：{user} 是用户，{npc} 是 NPC，{narration} 是旁白。",
  "",
  "硬规则：",
  "1. 用户最新消息点名了谁，谁必须进 responders。昵称、简称、部分匹配也算。",
  "2. 如果用户明显是在接上一轮某个 NPC 的话，即使没点名，该 NPC 也必须进 responders。",
  "3. 如果用户没指向任何 NPC，responders 可以为空数组。",
  "4. responders 里出现了不在固定 NPC 列表中的名字，它必须同时出现在 spawn_npcs 中。",
  "5. responders 数组本身就是发言顺序，越靠前越先说。顺序必须合理，不能机械按固定名单顺序排。",
  "6. 用户口中的称呼、身份词、职业词、场景角色词，必须优先映射到已有固定 NPC 或场内 NPC，而不是轻易新建人。",
  "7. 只要已有 NPC 的名字、角色描述、身份设定、职责定位能合理承接这个称呼，就必须直接使用那个已有 NPC 的真实名字写入 responders。",
  "8. spawn_npcs 只能用于场内确实没有合适现成人物可接这个称呼的情况。",
  "",
  "顺序判断优先级：",
  "- 被用户直接点名、追问、质疑的人优先。",
  "- 上一轮刚和用户对话、现在最像被接话的人优先。",
  "- 更贴近当前动作、事件中心、身份更强势的人可以优先。",
  "- 其他 NPC 用来补充、附和、反驳、收尾。",
  "",
  "narration 规则：",
  "- 只写一句很短的动作/环境/气氛描写，也可以直接写空字符串。",
  "- 绝对不能写 NPC 台词。",
  "- 如果 responder 已经要亲自开口，narration 只写极简动作，不要提前剧透他说什么。",
  "- 如果与已有旁白高度重复，优先写空字符串。",
  "",
  "spawn_npcs 规则：",
  "- 只在确实需要临时 NPC 回话时生成。",
  "- 在生成前，先检查固定 NPC 与场内 NPC 的名字、角色描述、职责、身份、立场是否已经能承接用户当前称呼。",
  "- 只要已有 NPC 可以合理承接，就不要新生一个同职能、同身份、同场景位置的人。",
  '- 格式固定为 [{"name":"名字","prompt":"一句话角色描述"}]。',
  "- prompt 简短，用中文。",
  "",
  "=== npc_instructions 规则（重要） ===",
  "npc_instructions 是一个对象，key 是 NPC 名字（必须在 responders 或 spawn_npcs 中出现），value 是你作为导演对那个 NPC 的具体要求。",
  "用途示例：",
  '- 用户说"给我简单说下" → 导演可以要求该 NPC "控制在 50 字以内，简洁回答"',
  '- 用户提问某个话题 → 导演可以要求对应 NPC "侧重解释 X 方面，语气要耐心"',
  '- 用户要求激烈争吵 → 导演可以要求对应 NPC "语气要愤怒，多质问对方"',
  '- 用户不想太长 → 导演要求所有 NPC "每句话控制在 30 字以内"',
  "- 如果不需对某个 NPC 提额外要求，可以不写该 NPC 的 key，或 npc_instructions 设为 {}。",
  "",
  "正确示例：",
  '用户: "小翠，给我倒杯茶，简短说" → {"narration":"小翠应了一声，提起茶壶。","responders":["小翠"],"spawn_npcs":[],"npc_instructions":{"小翠":"控制在15字以内，简洁回应"}}',
  '用户: "老板，你这菜多少钱？给我算便宜点"；固定 NPC 有"老板" → {"narration":"柜台后有人抬了下眼。","responders":["老板"],"spawn_npcs":[],"npc_instructions":{"老板":"语气要精明，带点生意人的算计，回应价格话题"}}',
  '用户: "你们俩都说说看法" → {"narration":"","responders":["春桃","小翠"],"spawn_npcs":[],"npc_instructions":{"春桃":"侧重分析利弊，理性","小翠":"从感情角度出发，感性"}}',
  "",
  "最后再提醒一次：只输出 JSON 对象本身，一行。"
].join("\n");

const WORK_DIRECTOR_SYSTEM_PROMPT = [
  "你是工作会话的导演调度器。你的唯一输出必须是一个 JSON 对象。",
  "禁止输出自然语言、解释、markdown、代码块、旁白前缀。",
  "输出格式固定：",
  '{"narration":"","responders":["先说话的NPC","后说话的NPC"],"spawn_npcs":[{"name":"临时NPC名","prompt":"一句话角色描述"}],"npc_instructions":{"NPC名":"给这个NPC的简短执行要求"}}',
  "",
  "你的任务很简单：根据用户最新需求，安排这一轮由谁回答、顺序怎样、每个 NPC 负责什么。",
  "重点是调度清楚、分工明确、响应直接，不要写剧情导演式的复杂规则或氛围化指令。",
  "",
  "硬规则：",
  "1. responders 只列本轮需要回答的 NPC，顺序就是发言顺序。",
  "2. 如果用户点名了某个 NPC，该 NPC 必须进入 responders。",
  "3. 如果用户要求多人协作，可以安排多个 NPC，顺序按任务流转来排。",
  "4. 优先复用已有固定 NPC 或场内 NPC，不要随便新建临时 NPC。",
  "5. spawn_npcs 只在现有 NPC 确实无法承接任务时才使用。",
  "6. npc_instructions 只写简短执行要求，例如“先给结论，再补两条理由”或“负责指出风险”。",
  "7. narration 默认写空字符串；除非确实需要一句极短过渡，否则不要写。",
  "8. 只输出合法 JSON，不要附加任何说明。",
].join("\n");

function getDirectorSystemPrompt(session) {
  return session?.mode === SESSION_MODE_WORK
    ? WORK_DIRECTOR_SYSTEM_PROMPT
    : STORY_DIRECTOR_SYSTEM_PROMPT;
}

const SESSION_MODE_STORY = "story";
const SESSION_MODE_WORK = "work";
